/*
Tickle
Copyright (C) 2017 Nick Robinson

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/
package uk.co.nickthecoder.tickle.demo

import uk.co.nickthecoder.tickle.AbstractProducer
import uk.co.nickthecoder.tickle.editor.EditorMain

class Demo : AbstractProducer() {

    init {
        instance = this
    }

    companion object {
        /**
         * A convenience, so that game code can easily get access to the game.
         */
        lateinit var instance: Demo
    }
}

/**
 * This is the main entry point for the Tickle demo.
 *
 * Your own game should contain a similar main entry point, which also calls Tickle,
 * but instead of passing the programName "tickle", it should pass the name of your game.
 *
 * Note. The programName must be the same name as the script generated by gradle installApp
 * (which is simply the name of the directory that the build.gradle script is contained within).
 */
fun main(args: Array<String>) {
    EditorMain("demo", args).start()
}
